### ISSUE TITLE
前端无法连接后端，可能是什么原因？

### ISSUE THREAD

**Issue by AlanLu0808** [llmapp/openai.mini#12]
我把后端跑起来了，用代码测试了后端可以连接。服务开在了8913端口上。
执行测试脚本
curl http://10.227.153.211:8913/api/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "Qwen-7B-Chat",
    "messages": [{"role": "user", "content": "Hello! What is your name?"}]
  }'可以得到正确的返回结果

但是使用前端连接的时候，输入消息后，回复信息一直在等待，不显示信息
![image](https://github.com/llmapp/openai.mini/assets/17940005/59287c0e-911f-4bd2-96c2-289434b2e245)

后端输出：
INFO:     10.56.112.161:3358 - "GET /index.html?model=qwen-7b HTTP/1.1" 304 Not Modified
INFO:     10.56.112.161:3358 - "GET /static/js/main.2203cc07.js HTTP/1.1" 304 Not Modified
INFO:     10.56.112.161:3358 - "GET /api/v1/plugins HTTP/1.1" 200 OK

浏览器console输出报错信息

index.tsx:49     POST http://0.0.0.0:8913/api/v1/chat/completions net::ERR_EMPTY_RESPONSE
index.tsx:49     POST http://0.0.0.0:8913/api/v1/chat/completions net::ERR_EMPTY_RESPONSE

index.tsx:49     Uncaught (in promise) TypeError: Failed to fetch
    at index.tsx:49:1
    at d (index.tsx:49:1)
    at Generator.<anonymous> (index.tsx:49:1)
    at Generator.next (index.tsx:49:1)
    at m (index.tsx:49:1)
    at u (index.tsx:49:1)
    at index.tsx:49:1
    at new Promise (<anonymous>)
    at index.tsx:49:1
    at index.tsx:49:1

index.tsx:49     Uncaught (in promise) TypeError: Failed to fetch
    at index.tsx:49:1
    at d (index.tsx:49:1)
    at Generator.<anonymous> (index.tsx:49:1)
    at Generator.next (index.tsx:49:1)
    at m (index.tsx:49:1)
    at u (index.tsx:49:1)
    at index.tsx:49:1
    at new Promise (<anonymous>)
    at index.tsx:49:1
    at index.tsx:49:1

这可能是哪里除了问题呢？

**Comment by liaoweiguo** [comment]
IP配置的问题，要在本地执行，他连接的localhost的api

**Comment by AlanLu0808** [comment]
> IP配置的问题，要在本地执行，他连接的localhost的api

是的，搞定了，感谢！
