### ISSUE TITLE
请教一下哪里查看私有模型的能力？

### ISSUE THREAD

**Issue by swit1983** [llmapp/openai.mini#6]
比如模型拥有哪些系统定义的角色，是否支持function, 支持哪些指令， 他们都只是实现了transforms的接口吗？私有模型差异挺大的，如何实现统一呢？

**Comment by huajianmao** [comment]
一般在Huggingface上发布模型的时候，都会有一个`modeling_xxxx.py`的文件，里面会定义它的接口等。例如[Qwen的模型定义文件](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py)。另外在还会有一个`config.json`文件，里面会指定`pretrained`加载出来的`model`是哪个类，例如[Qwen](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/config.json#L9).

支持哪些定义的角色不一定会显式的定义出来吧，主要体现在了他训练语料的格式里了，但有一些模型会在文档里说明。

**Comment by swit1983** [comment]
万分感谢
