### ISSUE TITLE
function_call 属性在stream模式下没有实现

### ISSUE THREAD

**Issue by zhengxiang5965** [llmapp/openai.mini#7]
![image](https://github.com/llmapp/openai.mini/assets/31379313/33cb5229-1b19-4fd3-b3a6-d94b1a3cae7e)

**Comment by huajianmao** [comment]
是的，正在实现中。 

这个commit 14317e4637074133884ca275d9033e627b1cb05d 初步实现了一下。
但是，还有个小问题，就是参数里会带上(\nObservation:) 
![image](https://github.com/llmapp/openai.mini/assets/1352072/2d41e351-5408-4715-b389-f7e553ab8a91)

**Comment by huajianmao** [comment]
@zhengxiang5965  已经可以用了。
但目前实现的有些tricky，另外，受限于Qwen的能力，还经常会出错。
