### ISSUE TITLE
SDXL的插件没有了？

### ISSUE THREAD

**Issue by liaoweiguo** [llmapp/openai.mini#9]

**Comment by huajianmao** [comment]
有些人的机器内存不够，有时候自动触发SDXL插件而自动加载SDXL，导致内存爆掉了。
还没有写插件的手动选择模块，所以就临时性的删除了SDXL。

如果你的内存够，可以**恢复到上一个commit**，或者手动在`app/backend/plugin/plugins/`下，创建`SDXL.py`文件，文件内容为：
``` python
import openai
from typing import List

from ..type import Argument, Plugin

# load_dotenv()

# openai.api_key = os.getenv("OPENAI_API_KEY", "none")
# if os.getenv("OPENAI_API_BASE", None) is not None:
#     openai.api_base = os.getenv("OPENAI_API_BASE")

openai.api_key = "none"
openai.api_base = "http://localhost:8000/api/v1"

class SDXL(Plugin):
    name = "gen_image_with_sdxl"
    name_for_human = "SDXL图片生成"
    description = "根据用户输入的prompt内容生成图片"
    arguments: List[Argument] = [
        Argument(name="prompt", type="string", description="The prompt for generating image.", required=True),
        Argument(name="size", type="string", description="The size of the images to be generated.", required=False),
        Argument(name="count", type="number", description="The count of how many images to be generated.", required=False)
    ]

    def run(self, args: str) -> str or None:
        params = super().run(args)
        if params is None or "prompt" not in params:
            return None

        prompt = params["prompt"]
        size = params["size"] if "size" in params and params["size"] in [
            "1024x1024", "512x512", "256x256"] else "1024x1024"
        count = params["count"] if "count" in params and type(params["count"]) == int else 1

        return openai.Image.create(prompt=prompt, n=count, size=size)
```

**Comment by liaoweiguo** [comment]
这个插件输出的图片，在界面怎么显示的，现在用的localhost，在其他机器上显示不了，因为浏览器不在服务器上

![image](https://github.com/llmapp/openai.mini/assets/22187224/d6363c08-e6e9-48bf-95a8-a9e691905ce9)

**Comment by huajianmao** [comment]
``` python
openai.api_key = "none"
openai.api_base = "http://localhost:8000/api/v1"
```

设置这里的时候，不要用`localhost`，用具体的地址。

发布的有些匆忙了。

**Comment by huajianmao** [comment]
我正在重新整理前端的代码，尽快放出来。

**Comment by liaoweiguo** [comment]
<img src="http://10.8.x.xxx:8000/images/image-d118f59c61f14599b8abd2c16d4fd750.jpg" />

这个图片在ubuntu chrome和edge中都显示不了，记得当时用下面的可以
f'<img src="file={_filename}" style="max-height: 100%; max-width: 100%;">'

**Comment by liaoweiguo** [comment]
<img src="http://10.8.x.xxx:8000/images/image-d118f59c61f14599b8abd2c16d4fd750.jpg" />

这个图片在ubuntu chrome和edge中都显示不了，记得当时用下面的可以
f'<img src="file={_filename}" style="max-height: 100%; max-width: 100%;">'

**Comment by huajianmao** [comment]
存在一种可能，就是下面的结果输出里的 URL 是 大模型幻觉输出的。

你展开插件，看一下插件里的输出地址是啥。那个地址，理论上是可以访问的。
另外，你可以看一下服务器上`IMAGE_FOLDER = "./files/images"` 这个目录里是不是有生成的文件了。

**Comment by liaoweiguo** [comment]
有输出，图片可以打开，只是最后页面上的img标签显示不了

如：
请画一匹骏马


Qwen-7B-Chat
Used gen_image_with_sdxl
好的，我已经为你生成了一张骏马的图片：[http://10.8.4.123:8000/images/image-ff1904829484463d899df8a736099ea2.jpg。如果你需要其他的图片，可以继续使用gen_image_with_sdxl工具。]

就是最终LLM输出的img标签显示不了

**Comment by huajianmao** [comment]
我最后是markdown形式展示的，我再qwen里当时也提了这个问题，qwen一直无法输出图片的markdown形式。

https://github.com/QwenLM/Qwen-7B/issues/186

**Comment by liaoweiguo** [comment]
> 我最后是markdown形式展示的，我再qwen里当时也提了这个问题，qwen一直无法输出图片的markdown形式。
> 
> [QwenLM/Qwen-7B#186](https://github.com/QwenLM/Qwen-7B/issues/186)

能不能在拿到插件输入以后自己展示？这部分代码能改吗

**Comment by huajianmao** [comment]
我尝试过让插件在拿到图片链接地址以后，再生成markdown格式的输出内容，然后再传给qwen，但qwen还是没输出希望的结果。

qwen的人员当时提了两个建议，但我觉得有些case相关，所以没采纳。

**Comment by huajianmao** [comment]
如果只有一个插件的话，那么可以解析这个结果，然后把图片链接替换成markdown格式，但插件可能会有很多，没中特殊情况都需要做特殊处理的话，可能就不太优雅了。所以还是等模型变强一些更靠谱

**Comment by liaoweiguo** [comment]
画图的模型可以放到CPU里面，我用的24G的4090，跟LLM一起加载不了，放CPU跑还凑合

class ImageModel(Model):
    pipeline: Any

    def load(self):
        model_id = compose_model_id(self.id, prefix=self.org)
        print(f"Loading model {model_id}")
        self.pipeline = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16, use_safetensors=True, variant="fp16")
        # self.pipeline.to("cuda")
        self.pipeline.enable_model_cpu_offload()
        print(f"Model {model_id} loaded!")
